import type {
  AdminPermission,
  AdminRole,
  AdminSectionConfig,
  AdminSeedData,
  RoleDefinition,
} from './types';

const now = new Date();

const isoOffset = (days: number, hours = 0): string =>
  new Date(now.getTime() + days * 24 * 60 * 60 * 1000 + hours * 60 * 60 * 1000).toISOString();

export const ROLE_PERMISSION_MAP = {
  super_admin: [
    'overview.view',
    'catalog.manage',
    'playlists.manage',
    'artists.manage',
    'discovery.manage',
    'moderation.manage',
    'users.manage',
    'analytics.view',
    'flags.manage',
    'promotions.manage',
    'notifications.manage',
    'roles.manage',
    'platform.view',
  ],
  content_editor: [
    'overview.view',
    'catalog.manage',
    'playlists.manage',
    'artists.manage',
    'discovery.manage',
    'analytics.view',
    'promotions.manage',
    'notifications.manage',
    'platform.view',
  ],
  moderator: [
    'overview.view',
    'moderation.manage',
    'users.manage',
    'analytics.view',
    'platform.view',
  ],
  analyst: [
    'overview.view',
    'analytics.view',
    'discovery.manage',
    'platform.view',
  ],
} satisfies Record<AdminRole, AdminPermission[]>;

export const ROLE_DEFINITIONS: RoleDefinition[] = [
  {
    role: 'super_admin',
    label: 'Super Admin',
    description: 'Owns release gates, configuration, and cross-functional platform controls.',
    permissions: ROLE_PERMISSION_MAP.super_admin,
  },
  {
    role: 'content_editor',
    label: 'Content Editor',
    description: 'Curates catalog, playlists, banners, and editorial publishing schedules.',
    permissions: ROLE_PERMISSION_MAP.content_editor,
  },
  {
    role: 'moderator',
    label: 'Moderator',
    description: 'Triages reports, abuse signals, account actions, and takedown operations.',
    permissions: ROLE_PERMISSION_MAP.moderator,
  },
  {
    role: 'analyst',
    label: 'Analyst',
    description: 'Monitors growth, retention, search quality, and experiment readouts.',
    permissions: ROLE_PERMISSION_MAP.analyst,
  },
];

export const ADMIN_SECTIONS: AdminSectionConfig[] = [
  {
    key: 'overview',
    label: 'Overview',
    shortLabel: 'Home',
    group: 'Monitor',
    description: 'Executive snapshot for catalog health, traffic, and system reliability.',
    permission: 'overview.view',
    keywords: ['dashboard', 'overview', 'health', 'growth', 'streams'],
  },
  {
    key: 'songs',
    label: 'Song CMS',
    shortLabel: 'Songs',
    group: 'Catalog',
    description: 'Metadata editing, bulk imports, approval workflow, and availability controls.',
    permission: 'catalog.manage',
    keywords: ['catalog', 'songs', 'metadata', 'bulk import', 'regions'],
  },
  {
    key: 'playlists',
    label: 'Playlists',
    shortLabel: 'Playlists',
    group: 'Catalog',
    description: 'Editorial ordering, homepage pushes, scheduling, and category management.',
    permission: 'playlists.manage',
    keywords: ['playlists', 'editorial', 'homepage', 'schedule'],
  },
  {
    key: 'artists',
    label: 'Artists',
    shortLabel: 'Artists',
    group: 'Catalog',
    description: 'Verified controls, profile quality, discography integrity, and reach.',
    permission: 'artists.manage',
    keywords: ['artists', 'verified', 'discography', 'profiles'],
  },
  {
    key: 'discovery',
    label: 'Discovery',
    shortLabel: 'Search',
    group: 'Growth',
    description: 'Search weights, typo mapping, keyword momentum, and curated boosts.',
    permission: 'discovery.manage',
    keywords: ['search', 'discovery', 'ranking', 'keywords', 'tokens'],
  },
  {
    key: 'moderation',
    label: 'Moderation',
    shortLabel: 'Trust',
    group: 'Trust',
    description: 'Reported content queue, copyright review, duplicates, and fraud signals.',
    permission: 'moderation.manage',
    keywords: ['moderation', 'copyright', 'reports', 'fraud', 'duplicates'],
  },
  {
    key: 'users',
    label: 'Users',
    shortLabel: 'Users',
    group: 'Trust',
    description: 'Premium mix, user reports, lifecycle health, and moderation actions.',
    permission: 'users.manage',
    keywords: ['users', 'accounts', 'premium', 'reports'],
  },
  {
    key: 'analytics',
    label: 'Analytics',
    shortLabel: 'Analytics',
    group: 'Monitor',
    description: 'Streaming trends, retention, market mix, and real-time activity.',
    permission: 'analytics.view',
    keywords: ['analytics', 'retention', 'countries', 'realtime'],
  },
  {
    key: 'flags',
    label: 'Feature Flags',
    shortLabel: 'Flags',
    group: 'Release',
    description: 'Remote config, beta rollouts, platform toggles, and OTA channels.',
    permission: 'flags.manage',
    keywords: ['flags', 'remote config', 'ota', 'rollout', 'beta'],
  },
  {
    key: 'promotions',
    label: 'Promotions',
    shortLabel: 'Promotions',
    group: 'Growth',
    description: 'Home banners, launch campaigns, placements, and visual previews.',
    permission: 'promotions.manage',
    keywords: ['banners', 'promotions', 'campaigns', 'placements'],
  },
  {
    key: 'notifications',
    label: 'Notifications',
    shortLabel: 'Notify',
    group: 'Growth',
    description: 'Push campaigns, release alerts, segment targeting, and delivery logs.',
    permission: 'notifications.manage',
    keywords: ['notifications', 'push', 'segments', 'alerts'],
  },
  {
    key: 'roles',
    label: 'Admin Roles',
    shortLabel: 'Roles',
    group: 'Security',
    description: 'Permission model, audit timeline, workflow policy, and Firestore architecture.',
    permission: 'roles.manage',
    keywords: ['roles', 'permissions', 'audit', 'architecture', 'firestore'],
  },
];

export const createAdminSeed = (): AdminSeedData => ({
  overviewMetrics: [
    {
      key: 'catalog_songs',
      label: 'Total songs',
      value: '182.4K',
      delta: '+3.8% WoW',
      detail: '284 waiting for final approval',
      status: 'positive',
    },
    {
      key: 'editorial_playlists',
      label: 'Total playlists',
      value: '6.1K',
      delta: '+41 this week',
      detail: '18 scheduled for homepage rotation',
      status: 'positive',
    },
    {
      key: 'active_users',
      label: 'Active users',
      value: '42.8K',
      delta: '+8.6% DAU',
      detail: 'Premium share 31.4%',
      status: 'positive',
    },
    {
      key: 'streams_today',
      label: 'Streams today',
      value: '1.84M',
      delta: '+12.1% vs yesterday',
      detail: 'Peak concurrency 28.2K',
      status: 'positive',
    },
    {
      key: 'search_precision',
      label: 'Search precision',
      value: '92.4%',
      delta: '+1.2 pts',
      detail: 'Misspelling hit-rate 84%',
      status: 'neutral',
    },
    {
      key: 'system_health',
      label: 'System health',
      value: '99.98%',
      delta: 'All core paths green',
      detail: 'Ingest SLA 6m median',
      status: 'positive',
    },
  ],
  growthSeries: [
    { label: 'Apr 18', primary: 960, secondary: 430 },
    { label: 'Apr 19', primary: 1010, secondary: 448 },
    { label: 'Apr 20', primary: 995, secondary: 452 },
    { label: 'Apr 21', primary: 1088, secondary: 470 },
    { label: 'Apr 22', primary: 1132, secondary: 488 },
    { label: 'Apr 23', primary: 1174, secondary: 505 },
    { label: 'Apr 24', primary: 1230, secondary: 522 },
  ],
  engagementSeries: [
    { label: '00:00', primary: 42, secondary: 17 },
    { label: '04:00', primary: 28, secondary: 10 },
    { label: '08:00', primary: 54, secondary: 21 },
    { label: '12:00', primary: 76, secondary: 29 },
    { label: '16:00', primary: 92, secondary: 33 },
    { label: '20:00', primary: 88, secondary: 31 },
    { label: '23:00', primary: 61, secondary: 22 },
  ],
  searchTrends: [
    { keyword: 'lofi coding hindi', lift: '+28%', searchCount: '18.2K', intent: 'focus playlist' },
    { keyword: 'afrobeats gym mix', lift: '+22%', searchCount: '13.4K', intent: 'editorial opportunity' },
    { keyword: 'sufi midnight drive', lift: '+16%', searchCount: '9.1K', intent: 'new mood lane' },
    { keyword: 'retro tamil rain', lift: '+12%', searchCount: '7.8K', intent: 'regional momentum' },
  ],
  healthSignals: [
    { label: 'Catalog ingest', value: '6m 12s', state: 'healthy', detail: 'Median completion across last 50 jobs' },
    { label: 'Search API p95', value: '84ms', state: 'healthy', detail: 'Stable after latest relevance rollout' },
    { label: 'Broken tracks', value: '14', state: 'warning', detail: '9 CDN mismatches and 5 rights blocks' },
    { label: 'Moderation backlog', value: '31', state: 'warning', detail: '8 high-priority reports need review' },
  ],
  recentContent: [
    { id: 'rc_1', title: 'Neon Drive Nights', kind: 'playlist', owner: 'Editorial India', state: 'scheduled', timestamp: isoOffset(1, 6) },
    { id: 'rc_2', title: 'Velvet Echoes', kind: 'song', owner: 'Catalog Ops', state: 'review', timestamp: isoOffset(0, -3) },
    { id: 'rc_3', title: 'Aarya Sen', kind: 'artist', owner: 'Artist Success', state: 'published', timestamp: isoOffset(-1, -6) },
    { id: 'rc_4', title: 'Summer Re-entry Banner', kind: 'banner', owner: 'Growth Studio', state: 'draft', timestamp: isoOffset(2, 0) },
  ],
  songs: [
    {
      id: 'song_1',
      title: 'Velvet Echoes',
      artist: 'Mira K',
      album: 'Late City Bloom',
      genre: 'Alt Pop',
      language: 'English',
      duration: '3:27',
      popularityScore: 91,
      releaseDate: '2026-04-18',
      explicit: false,
      approvalState: 'review',
      regions: ['IN', 'US', 'GB', 'AE'],
      broken: false,
      ingestionNote: 'Artwork checksum updated after label resubmission.',
    },
    {
      id: 'song_2',
      title: 'Afterglow Static',
      artist: 'Ruhan',
      album: 'Night Transit',
      genre: 'Synthwave',
      language: 'Hindi',
      duration: '4:02',
      popularityScore: 87,
      releaseDate: '2026-04-15',
      explicit: true,
      approvalState: 'published',
      regions: ['IN', 'CA', 'AU'],
      broken: false,
      ingestionNote: 'Published to homepage recommendations.',
    },
    {
      id: 'song_3',
      title: 'Monsoon Tapes',
      artist: 'Yuvaan Collective',
      album: 'Window Seat',
      genre: 'Indie',
      language: 'Tamil',
      duration: '2:58',
      popularityScore: 73,
      releaseDate: '2026-04-25',
      explicit: false,
      approvalState: 'scheduled',
      regions: ['IN', 'SG', 'MY'],
      broken: false,
      ingestionNote: 'Scheduled with Friday editorial push.',
    },
    {
      id: 'song_4',
      title: 'Faultline Memory',
      artist: 'Daev',
      album: 'Faultline Memory',
      genre: 'Electronic',
      language: 'English',
      duration: '3:51',
      popularityScore: 64,
      releaseDate: '2026-04-11',
      explicit: false,
      approvalState: 'draft',
      regions: ['US', 'DE'],
      broken: true,
      ingestionNote: 'Audio file hash mismatch detected on edge cache.',
    },
    {
      id: 'song_5',
      title: 'Raat Ke Signals',
      artist: 'Noor 77',
      album: 'Metro Hearts',
      genre: 'R&B',
      language: 'Hindi',
      duration: '3:18',
      popularityScore: 79,
      releaseDate: '2026-04-22',
      explicit: false,
      approvalState: 'published',
      regions: ['IN', 'AE', 'ZA'],
      broken: false,
      ingestionNote: 'Search tokens enriched for colloquial spellings.',
    },
  ],
  importJobs: [
    { id: 'job_1', label: 'Sony April batch 04A', source: 'CSV + WAV bundle', progress: 78, status: 'processing' },
    { id: 'job_2', label: 'Regional Tamil refresh', source: 'Label portal', progress: 42, status: 'processing' },
    { id: 'job_3', label: 'Broken track re-ingest', source: 'CDN repair queue', progress: 18, status: 'blocked' },
    { id: 'job_4', label: 'Indie spotlight intake', source: 'Manual upload', progress: 100, status: 'completed' },
  ],
  playlists: [
    {
      id: 'pl_1',
      name: 'Night Shift Focus',
      curator: 'Editorial India',
      category: 'Focus',
      songCount: 38,
      trendingScore: 94,
      publishAt: isoOffset(1, 4),
      homepageSlot: 'Hero row / slot 1',
      approvalState: 'scheduled',
      listeners: '184K',
    },
    {
      id: 'pl_2',
      name: 'Coastal Morning Run',
      curator: 'Global Fitness',
      category: 'Workout',
      songCount: 52,
      trendingScore: 88,
      publishAt: isoOffset(0, -4),
      homepageSlot: 'Trending shelf',
      approvalState: 'published',
      listeners: '261K',
    },
    {
      id: 'pl_3',
      name: 'Retro Hindi Commute',
      curator: 'Classics Desk',
      category: 'Commute',
      songCount: 44,
      trendingScore: 81,
      publishAt: isoOffset(2, 2),
      homepageSlot: 'Regional shelf',
      approvalState: 'review',
      listeners: '96K',
    },
    {
      id: 'pl_4',
      name: 'Rain Room Tamil',
      curator: 'South Editorial',
      category: 'Mood',
      songCount: 31,
      trendingScore: 77,
      publishAt: isoOffset(-1, -3),
      homepageSlot: 'Late night module',
      approvalState: 'draft',
      listeners: '58K',
    },
  ],
  artists: [
    {
      id: 'ar_1',
      name: 'Mira K',
      verified: true,
      monthlyListeners: '4.8M',
      releaseVelocity: '2 releases / 30 days',
      topMarket: 'India',
      discographyCount: 27,
    },
    {
      id: 'ar_2',
      name: 'Ruhan',
      verified: true,
      monthlyListeners: '3.2M',
      releaseVelocity: '1 release / 45 days',
      topMarket: 'UAE',
      discographyCount: 19,
    },
    {
      id: 'ar_3',
      name: 'Yuvaan Collective',
      verified: false,
      monthlyListeners: '910K',
      releaseVelocity: '3 releases / 30 days',
      topMarket: 'Singapore',
      discographyCount: 11,
    },
    {
      id: 'ar_4',
      name: 'Noor 77',
      verified: true,
      monthlyListeners: '1.4M',
      releaseVelocity: '1 release / 60 days',
      topMarket: 'India',
      discographyCount: 14,
    },
  ],
  searchWeights: [
    { id: 'sw_1', label: 'Exact title match', value: 92, hint: 'High confidence intent signal' },
    { id: 'sw_2', label: 'Artist affinity', value: 76, hint: 'Boost when listener has prior saves' },
    { id: 'sw_3', label: 'Freshness', value: 58, hint: 'New releases within 21 days' },
    { id: 'sw_4', label: 'Editorial boost', value: 64, hint: 'Curated discovery and hero shelves' },
  ],
  curatedBoosts: [
    { id: 'cb_1', keyword: 'coding lofi', placement: 'Search hero', boost: 18, expiresAt: isoOffset(7, 0) },
    { id: 'cb_2', keyword: 'retro hindi', placement: 'Discovery shelf', boost: 12, expiresAt: isoOffset(14, 0) },
    { id: 'cb_3', keyword: 'afrobeats gym', placement: 'Workout row', boost: 21, expiresAt: isoOffset(5, 0) },
  ],
  typoMappings: [
    { id: 'tm_1', typo: 'afo beats', canonical: 'afrobeats', language: 'en' },
    { id: 'tm_2', typo: 'lofy', canonical: 'lofi', language: 'en' },
    { id: 'tm_3', typo: 'arrijit', canonical: 'arijit', language: 'hi' },
    { id: 'tm_4', typo: 'tamill', canonical: 'tamil', language: 'en' },
  ],
  searchTokens: ['chill-hop', 'night-drive', 'indie-pop', 'retro-hindi', 'focus-mode', 'sufi'],
  moderationCases: [
    {
      id: 'mc_1',
      entity: 'Faultline Memory',
      reason: 'Broken playback reports surged from Android 14',
      reporterType: 'User reports',
      severity: 'high',
      status: 'investigating',
      createdAt: isoOffset(0, -5),
    },
    {
      id: 'mc_2',
      entity: 'DJ Flux - mirrored upload',
      reason: 'Duplicate audio fingerprint collision',
      reporterType: 'Fingerprinting',
      severity: 'medium',
      status: 'new',
      createdAt: isoOffset(-1, -2),
    },
    {
      id: 'mc_3',
      entity: 'Sunroom B-sides',
      reason: 'Copyright takedown request pending legal review',
      reporterType: 'Rights holder',
      severity: 'high',
      status: 'escalated',
      createdAt: isoOffset(-2, -1),
    },
    {
      id: 'mc_4',
      entity: 'Account 98A4',
      reason: 'Abnormal save velocity to self-uploaded tracks',
      reporterType: 'Fraud monitor',
      severity: 'medium',
      status: 'resolved',
      createdAt: isoOffset(-3, -6),
    },
  ],
  fraudSignals: [
    { id: 'fs_1', title: 'Save-farm anomaly', detail: '42 accounts repeating identical playlist saves within 18m', score: '0.91' },
    { id: 'fs_2', title: 'Geo mismatch', detail: 'Upload origin differs from licensed territory for 3 releases', score: '0.74' },
    { id: 'fs_3', title: 'Bot search spike', detail: 'Unnatural search bursts for one artist alias from 2 ASNs', score: '0.68' },
  ],
  users: [
    {
      id: 'usr_1',
      name: 'Kavya Rao',
      plan: 'premium',
      country: 'India',
      language: 'Hindi',
      reports: 0,
      lastActiveAt: isoOffset(0, -1),
      status: 'healthy',
    },
    {
      id: 'usr_2',
      name: 'Leo Martin',
      plan: 'free',
      country: 'United Kingdom',
      language: 'English',
      reports: 1,
      lastActiveAt: isoOffset(0, -4),
      status: 'watch',
    },
    {
      id: 'usr_3',
      name: 'Aadhya Menon',
      plan: 'premium',
      country: 'India',
      language: 'Malayalam',
      reports: 0,
      lastActiveAt: isoOffset(0, -2),
      status: 'healthy',
    },
    {
      id: 'usr_4',
      name: 'Sami El-Hadi',
      plan: 'free',
      country: 'UAE',
      language: 'Arabic',
      reports: 3,
      lastActiveAt: isoOffset(-1, -8),
      status: 'restricted',
    },
  ],
  topSongs: [
    { id: 'ts_1', label: 'Raat Ke Signals', value: '412K streams', percent: 94, sublabel: 'Save rate 19.4%' },
    { id: 'ts_2', label: 'Afterglow Static', value: '366K streams', percent: 82, sublabel: 'Search entry 28%' },
    { id: 'ts_3', label: 'Velvet Echoes', value: '291K streams', percent: 68, sublabel: 'Editorial add 11 shelves' },
    { id: 'ts_4', label: 'Monsoon Tapes', value: '184K streams', percent: 47, sublabel: 'Scheduled lift forecast +22%' },
  ],
  topPlaylists: [
    { id: 'tp_1', label: 'Coastal Morning Run', value: '261K listeners', percent: 96, sublabel: 'Avg completion 64%' },
    { id: 'tp_2', label: 'Night Shift Focus', value: '184K listeners', percent: 74, sublabel: 'Follow-through 18%' },
    { id: 'tp_3', label: 'Retro Hindi Commute', value: '96K listeners', percent: 48, sublabel: 'CTR +11% after art swap' },
    { id: 'tp_4', label: 'Rain Room Tamil', value: '58K listeners', percent: 32, sublabel: 'Still in draft review' },
  ],
  geoInsights: [
    { id: 'geo_1', market: 'India', share: '54%', retention: '41%', dominantLanguage: 'Hindi' },
    { id: 'geo_2', market: 'UAE', share: '11%', retention: '36%', dominantLanguage: 'Arabic' },
    { id: 'geo_3', market: 'United States', share: '9%', retention: '34%', dominantLanguage: 'English' },
    { id: 'geo_4', market: 'Singapore', share: '6%', retention: '39%', dominantLanguage: 'Tamil' },
  ],
  realtimeEvents: [
    { id: 'rt_1', action: 'Playlist published', detail: 'Night Shift Focus moved to homepage slot 1', timestamp: isoOffset(0, -1) },
    { id: 'rt_2', action: 'Feature flag bumped', detail: 'lyrics_web rollout increased to 25%', timestamp: isoOffset(0, -2) },
    { id: 'rt_3', action: 'Moderation resolved', detail: 'Duplicate upload case mc_4 closed after takedown', timestamp: isoOffset(0, -4) },
    { id: 'rt_4', action: 'Search dictionary synced', detail: '18 new typo mappings promoted to production', timestamp: isoOffset(0, -6) },
  ],
  featureFlags: [
    {
      id: 'ff_1',
      name: 'lyrics_web',
      description: 'Inline synced lyrics on song page.',
      enabled: true,
      rollout: 25,
      targets: ['web'],
      owner: 'Growth Eng',
    },
    {
      id: 'ff_2',
      name: 'smart_queue_v2',
      description: 'Contextual next-up queue seeded by completion history.',
      enabled: true,
      rollout: 15,
      targets: ['web', 'android', 'ios'],
      owner: 'Playback ML',
    },
    {
      id: 'ff_3',
      name: 'artist_hub_refresh',
      description: 'New artist profile surfaces for verified talent.',
      enabled: false,
      rollout: 0,
      targets: ['web', 'ios'],
      owner: 'Artist Experience',
    },
  ],
  otaTracks: [
    { id: 'ota_1', name: 'Web release 2.4.0', channel: 'web', rollout: '100%', build: 'web-240', status: 'monitoring' },
    { id: 'ota_2', name: 'Android beta 1.9.7', channel: 'android', rollout: '35%', build: 'a-197b', status: 'ready' },
    { id: 'ota_3', name: 'iOS hotfix 1.9.6', channel: 'ios', rollout: '0%', build: 'i-196hf', status: 'paused' },
  ],
  banners: [
    {
      id: 'bn_1',
      title: 'Late City Bloom launch',
      placement: 'Home hero',
      status: 'scheduled',
      audience: 'Premium + alt-pop listeners',
      startAt: isoOffset(1, 2),
      endAt: isoOffset(8, 2),
      accent: '#49d5ff',
    },
    {
      id: 'bn_2',
      title: 'Mood playlist push',
      placement: 'Search interstitial',
      status: 'published',
      audience: 'High-intent searchers',
      startAt: isoOffset(-2, 0),
      endAt: isoOffset(5, 0),
      accent: '#7dffb1',
    },
    {
      id: 'bn_3',
      title: 'Retro commute takeover',
      placement: 'Regional shelf',
      status: 'draft',
      audience: 'Hindi commute segment',
      startAt: isoOffset(4, 0),
      endAt: isoOffset(11, 0),
      accent: '#8cb5ff',
    },
  ],
  notifications: [
    {
      id: 'nc_1',
      title: 'New release: Velvet Echoes',
      segment: 'Fans of Mira K',
      channel: 'push',
      status: 'scheduled',
      scheduledAt: isoOffset(0, 3),
      uplift: '+11% first-day plays',
    },
    {
      id: 'nc_2',
      title: 'Workout mix refresh',
      segment: 'Active runners',
      channel: 'in-app',
      status: 'sent',
      scheduledAt: isoOffset(-1, -4),
      uplift: '+8% session starts',
    },
    {
      id: 'nc_3',
      title: 'Premium weekend bundle',
      segment: 'Free power users',
      channel: 'push',
      status: 'draft',
      scheduledAt: isoOffset(2, 0),
      uplift: '+4.2% upgrade intent',
    },
  ],
  roleDefinitions: ROLE_DEFINITIONS,
  auditEvents: [
    { id: 'ae_1', actor: 'Anika Bose', role: 'super_admin', action: 'Approved playlist publish', entity: 'Night Shift Focus', timestamp: isoOffset(0, -1) },
    { id: 'ae_2', actor: 'Rizwan Ali', role: 'content_editor', action: 'Updated typo mappings', entity: 'search_terms/global', timestamp: isoOffset(0, -2) },
    { id: 'ae_3', actor: 'Mina George', role: 'moderator', action: 'Restricted account', entity: 'Account 98A4', timestamp: isoOffset(0, -4) },
    { id: 'ae_4', actor: 'Dev Patel', role: 'analyst', action: 'Published experiment readout', entity: 'smart_queue_v2', timestamp: isoOffset(-1, -3) },
  ],
  notes: [
    {
      id: 'note_1',
      author: 'Anika Bose',
      scope: 'Friday launch',
      body: 'Keep Late City Bloom hero capped at 18% traffic until lyric latency stays green for 3 hours.',
      createdAt: isoOffset(0, -2),
    },
    {
      id: 'note_2',
      author: 'Rizwan Ali',
      scope: 'Search ops',
      body: 'Promote retro hindi typo package after we finish QA on Urdu transliteration collisions.',
      createdAt: isoOffset(-1, -5),
    },
  ],
  firestoreCollections: [
    {
      path: 'admins/{uid}',
      purpose: 'Admin role assignment, status, permission overrides, and operator metadata.',
      keyFields: ['role', 'permissions', 'status', 'lastSeenAt', 'updatedAt'],
    },
    {
      path: 'artists/{artistId}',
      purpose: 'Canonical artist profile, verification status, audience stats, and discography references.',
      keyFields: ['name', 'verified', 'monthlyListeners', 'topMarkets', 'updatedAt'],
    },
    {
      path: 'search_terms/{termId}',
      purpose: 'Trending keywords, canonical spellings, redirect logic, and discovery boost metadata.',
      keyFields: ['term', 'normalizedTerm', 'boost', 'status', 'updatedAt'],
    },
    {
      path: 'moderation_cases/{caseId}',
      purpose: 'Unified review queue for reports, takedowns, duplicate detection, and abuse actions.',
      keyFields: ['entityType', 'status', 'severity', 'owner', 'createdAt'],
    },
    {
      path: 'feature_flags/{flagId}',
      purpose: 'Remote config toggles, platform targeting, and rollout percentages.',
      keyFields: ['enabled', 'targets', 'rollout', 'owner', 'updatedAt'],
    },
    {
      path: 'home_banners/{bannerId}',
      purpose: 'Home hero cards, promotional placements, scheduling, and creative references.',
      keyFields: ['placement', 'status', 'startAt', 'endAt', 'updatedAt'],
    },
    {
      path: 'notification_campaigns/{campaignId}',
      purpose: 'Push and in-app campaign payloads, audience definitions, and delivery status.',
      keyFields: ['status', 'segmentId', 'scheduledAt', 'sentAt', 'updatedAt'],
    },
    {
      path: 'admin_audit_logs/{eventId}',
      purpose: 'Immutable activity trail for privileged actions and state changes.',
      keyFields: ['actorId', 'actorRole', 'entityType', 'action', 'createdAt'],
    },
  ],
  indexRecommendations: [
    {
      collection: 'songs',
      fields: ['approvalState ASC', 'updatedAt DESC'],
      purpose: 'Review queue sorting for pending catalog edits.',
    },
    {
      collection: 'songs',
      fields: ['broken ASC', 'updatedAt DESC'],
      purpose: 'Broken-track detector and repair backlog.',
    },
    {
      collection: 'playlists',
      fields: ['approvalState ASC', 'publishAt ASC'],
      purpose: 'Scheduled playlist publishing calendar.',
    },
    {
      collection: 'artists',
      fields: ['verified ASC', 'monthlyListeners DESC'],
      purpose: 'Verified artist controls and analytics ranking.',
    },
    {
      collection: 'search_terms',
      fields: ['status ASC', 'updatedAt DESC'],
      purpose: 'Search dictionary review and rollout queue.',
    },
    {
      collection: 'moderation_cases',
      fields: ['status ASC', 'severity DESC', 'createdAt DESC'],
      purpose: 'Trust and safety triage board.',
    },
    {
      collection: 'users',
      fields: ['plan ASC', 'lastActiveAt DESC'],
      purpose: 'Premium/free mix and account health reviews.',
    },
    {
      collection: 'feature_flags',
      fields: ['enabled ASC', 'updatedAt DESC'],
      purpose: 'Remote config dashboard and rollback controls.',
    },
    {
      collection: 'home_banners',
      fields: ['placement ASC', 'startAt DESC'],
      purpose: 'Banner scheduling and homepage placement lookup.',
    },
    {
      collection: 'notification_campaigns',
      fields: ['status ASC', 'scheduledAt DESC'],
      purpose: 'Notification calendar and send logs.',
    },
  ],
  securityConsiderations: [
    'Keep `admins/{uid}` read-only from clients. Provision roles and overrides through Firebase Admin SDK or a trusted backend.',
    'Use custom claims only for coarse gating. Store fine-grained permissions and status overrides in Firestore for auditability.',
    'Write all privileged mutations through Cloud Functions or verified backend routes when the action touches multiple collections.',
    'Mirror every state-changing admin action into `admin_audit_logs` with actor, entity, before/after summary, and request trace id.',
    'Split public catalog reads from admin-only operational data so app traffic never shares indexes with internal dashboards.',
  ],
  folderStructure: [
    'frontend/src/features/admin/',
    'frontend/src/features/admin/components/',
    'frontend/src/features/admin/hooks/',
    'frontend/src/features/admin/services/',
    'frontend/src/features/admin/types.ts',
    'frontend/src/features/admin/mock-data.ts',
    'backend/src/routes/admin/',
    'backend/src/services/admin/',
    'docs/admin-dashboard-architecture.md',
  ],
  workflowStages: [
    { label: 'Draft', detail: 'Created by editorial or ingest job and not yet reviewable by other teams.' },
    { label: 'Review', detail: 'Awaiting content validation, rights checks, and quality assurance.' },
    { label: 'Scheduled', detail: 'Approved and attached to a publish window or rollout plan.' },
    { label: 'Published', detail: 'Live in one or more client surfaces with monitoring enabled.' },
    { label: 'Retired', detail: 'Removed from active circulation but preserved for audit and analytics.' },
  ],
});
