// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxNpulNTpThBy1fR21q4DsHFgjGW8LThs',
    appId: '1:816396705670:web:8e6a960d16ff066f521607',
    messagingSenderId: '816396705670',
    projectId: 'spotify-8fefc',
    authDomain: 'spotify-8fefc.firebaseapp.com',
    storageBucket: 'spotify-8fefc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxNpulNTpThBy1fR21q4DsHFgjGW8LThs',
    appId: '1:816396705670:android:8e6a960d16ff066f521607',
    messagingSenderId: '816396705670',
    projectId: 'spotify-8fefc',
    storageBucket: 'spotify-8fefc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxNpulNTpThBy1fR21q4DsHFgjGW8LThs',
    appId: '1:816396705670:ios:8e6a960d16ff066f521607',
    messagingSenderId: '816396705670',
    projectId: 'spotify-8fefc',
    storageBucket: 'spotify-8fefc.firebasestorage.app',
    iosBundleId: 'com.mavrixfy.mavrixfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxNpulNTpThBy1fR21q4DsHFgjGW8LThs',
    appId: '1:816396705670:ios:8e6a960d16ff066f521607',
    messagingSenderId: '816396705670',
    projectId: 'spotify-8fefc',
    storageBucket: 'spotify-8fefc.firebasestorage.app',
    iosBundleId: 'com.mavrixfy.mavrixfy',
  );
}